logging:
  level:
    org.springframework: DEBUG


server:
  port: 8082

jpa:
  hibernate:
    mysql:
      driver: com.mysql.cj.jdbc.Driver
      url: ${MYSQL_URL:}
      username: ${MYSQL_USER:}
      password: ${MYSQL_PASSWORD}
    showSql: true
    autoStrategy: create
    dialect: org.hibernate.dialect.MySQLDialect